"""Stable, non-sensitive Recommendation Agent errors."""

from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    INVALID_REQUEST = "INVALID_REQUEST"
    REQUEST_TOO_LARGE = "REQUEST_TOO_LARGE"
    RESPONSE_TOO_LARGE = "RESPONSE_TOO_LARGE"
    SERVICE_NOT_READY = "SERVICE_NOT_READY"
    SERVICE_OVERLOADED = "SERVICE_OVERLOADED"
    UNSUPPORTED_AGENT_VERSION = "UNSUPPORTED_AGENT_VERSION"
    UNSUPPORTED_FEATURE_VERSION = "UNSUPPORTED_FEATURE_VERSION"
    DEADLINE_EXPIRED = "DEADLINE_EXPIRED"
    DEADLINE_INSUFFICIENT = "DEADLINE_INSUFFICIENT"
    DEADLINE_EXHAUSTED = "DEADLINE_EXHAUSTED"
    INFERENCE_CONNECTION_FAILED = "INFERENCE_CONNECTION_FAILED"
    INFERENCE_TIMEOUT = "INFERENCE_TIMEOUT"
    INFERENCE_HTTP_ERROR = "INFERENCE_HTTP_ERROR"
    INFERENCE_MALFORMED_RESPONSE = "INFERENCE_MALFORMED_RESPONSE"
    INFERENCE_RESPONSE_TOO_LARGE = "INFERENCE_RESPONSE_TOO_LARGE"
    INFERENCE_UNAVAILABLE = "INFERENCE_UNAVAILABLE"
    INFERENCE_CONTRACT_MISMATCH = "INFERENCE_CONTRACT_MISMATCH"
    MODEL_VERSION_MISMATCH = "MODEL_VERSION_MISMATCH"
    MODEL_PACKAGE_MISMATCH = "MODEL_PACKAGE_MISMATCH"
    FEATURE_VERSION_MISMATCH = "FEATURE_VERSION_MISMATCH"
    MODEL_KEY_VERSION_MISMATCH = "MODEL_KEY_VERSION_MISMATCH"
    UNKNOWN_CANDIDATE = "UNKNOWN_CANDIDATE"
    DUPLICATE_CANDIDATE = "DUPLICATE_CANDIDATE"
    MISSING_CANDIDATE = "MISSING_CANDIDATE"
    INVALID_PROBABILITY = "INVALID_PROBABILITY"
    INVALID_EVIDENCE = "INVALID_EVIDENCE"
    RESULT_SELECTION_FAILED = "RESULT_SELECTION_FAILED"
    UNSUPPORTED_REASON = "UNSUPPORTED_REASON"
    UNSAFE_TEMPLATE = "UNSAFE_TEMPLATE"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class AgentError(Exception):
    """An allow-listed failure safe to map to an API response."""

    def __init__(
        self,
        code: ErrorCode,
        *,
        http_status: int,
        retryable: bool = False,
        failure_content: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(code.value)
        self.code = code
        self.http_status = http_status
        self.retryable = retryable
        self.failure_content = failure_content
