"""Domain layer — models, enums, and error contracts.

This package defines the core vocabulary shared across every business module:
strictly validated data models, domain enums, and stable error codes.

Re-exports the public API so callers only need one import:
  >>> from cooking_plan_agent.domain import CookingTask, DomainErrorCode, WorkMode
"""

from cooking_plan_agent.domain.enums import (
    HeatLevel,
    PlanStatus,
    SolverStatus,
    WorkMode,
)
from cooking_plan_agent.domain.errors import DomainErrorCode, WorkflowException
from cooking_plan_agent.domain.models import (
    Assumption,
    CompletionItem,
    Confidence,
    ConfirmationPlanResponse,
    CookingEvidence,
    CookingTask,
    EvidenceQuery,
    EvidenceRef,
    EvidenceResult,
    ExtractedIngredient,
    ExtractedRecipeCandidate,
    ExtractedStep,
    FailedPlanResponse,
    FeasibilityReport,
    GeneratePlanRequest,
    InfeasiblePlanResponse,
    IngredientDemand,
    IngredientFeasibility,
    InventoryConsumptionProposal,
    InventoryLotSnapshot,
    KitchenResourceSnapshot,
    LotAllocation,
    PlanResponse,
    PositiveDecimal,
    ReadyPlanResponse,
    RecipeGap,
    RecipeIR,
    RecipeStep,
    ReconciledEvidence,
    RepairOption,
    ResourceNeed,
    SafetyContext,
    SafetyFinding,
    SafetyReport,
    StrictModel,
    TaskDependency,
    WorkflowError,
)

__all__ = [
    "Assumption",
    "CompletionItem",
    "Confidence",
    "ConfirmationPlanResponse",
    "CookingEvidence",
    "CookingTask",
    "DomainErrorCode",
    "EvidenceQuery",
    "EvidenceRef",
    "EvidenceResult",
    "ExtractedIngredient",
    "ExtractedRecipeCandidate",
    "ExtractedStep",
    "FailedPlanResponse",
    "FeasibilityReport",
    "GeneratePlanRequest",
    "HeatLevel",
    "InfeasiblePlanResponse",
    "IngredientDemand",
    "IngredientFeasibility",
    "InventoryConsumptionProposal",
    "InventoryLotSnapshot",
    "KitchenResourceSnapshot",
    "LotAllocation",
    "PlanResponse",
    "PlanStatus",
    "PositiveDecimal",
    "ReadyPlanResponse",
    "RecipeGap",
    "RecipeIR",
    "RecipeStep",
    "ReconciledEvidence",
    "RepairOption",
    "ResourceNeed",
    "SafetyContext",
    "SafetyFinding",
    "SafetyReport",
    "SolverStatus",
    "StrictModel",
    "TaskDependency",
    "WorkflowError",
    "WorkflowException",
    "WorkMode",
]
